### ISSUE TITLE
instructions.md file doesn't load on Ubuntu 16 (Linux)

### ISSUE THREAD

**Issue by stitchng** [adonisjs/adonis-addon#4]
When using `adonis install` command to install an addon, the **instructions.md** file is not being loaded properly from the `/tmp/` OS data directory. It works well on _Windows_ & _MacOS_ except _Linux_ (Ubuntu 16 as test case)

Can you have this investigated ?

Please find attached below a screen shot of the occurrence on Ubuntu 16

Thank you

![Screenshot from 2019-03-08 16-40-25](https://user-images.githubusercontent.com/32128837/54071089-587b0500-4268-11e9-9bd6-b00836f4efe5.png)

**Comment by stitchng** [comment]
I believe this issue should be attended to as soon as possible @tutlage

**Comment by stitchng** [comment]
I believe this issue should be attended to as soon as possible @thetutlage

**Comment by thetutlage** [comment]
Not using `Ubuntu` daily, so couple of questions.

1. Can you normally open tmp files in browser?
2. Does the file exists in the `tmp` folder at all?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.

**Comment by stitchng** [comment]
1) Yes
2) No

In reply to @thetutlage
